backend/mlarchive/archive/urls.py
from django.urls import path 
from django.views.generic import TemplateView

from mlarchive.archive import ajax
from mlarchive.archive import views


urlpatterns = [
    path('ajax/msg/', ajax.ajax_get_msg, name='ajax_get_msg'),
    path('ajax/messages/', ajax.ajax_messages, name='ajax_messages'),
    path('ajax/admin/action/', ajax.ajax_admin_action, name='ajax_admin_action'),

    path('', views.main, name='archive'),
    path('admin/', views.admin, name='archive_admin'),
    path('admin/guide/', views.admin_guide, name='archive_admin_guide'),
    path('admin/console/', views.admin_console, name='archive_admin_console'),
    path('advsearch/', views.advsearch, name='archive_advsearch'),
    path('browse/', views.browse, name='archive_browse'),
    path('browse/static/', views.browse_static, name='archive_browse_static'),
    path('browse/<list_name>/', views.CustomBrowseView.as_view(), name='archive_browse_list'),
    path('browse/static/<list_name>/', views.browse_static_redirect, name='archive_browse_static'),
    path('browse/static/<list_name>/thread/', views.browse_static_thread_redirect, name='archive_browse_static_thread_redirect'),
    path('browse/static/<list_name>/<date>/', views.DateStaticIndexView.as_view(), name='archive_browse_static_date'),
    path('browse/static/<list_name>/thread/<date>/', views.ThreadStaticIndexView.as_view(), name='archive_browse_static_thread'),
    path('export/<type>/', views.export, name='archive_export'),
    path('help/', TemplateView.as_view(template_name="archive/help.html"), name='archive_help'),
    path('legacy/msg/<list_name>/<id>/', views.legacy_message, name='archive_legacy_message'),
    path('logout/', views.logout_view, name='archive_logout'),
    # url(r'^msg/(?P<list_name>[a-z0-9_\-\+]+)/(?P<id>[a-zA-Z0-9_\-]+)(=)?(/)?$', views.detail, name='archive_detail'),
    # url(r'^msg/(?P<list_name>[a-z0-9_\-\+]+)/(?P<id>[a-zA-Z0-9_\-]+)(=)?/(?P<sequence>\d+)(/)?$', views.attachment, name='a
    path('msg/<list_name>/<id>/', views.detail, name='archive_detail'),
    path('msg/<list_name>/<id>/<int:sequence>/', views.attachment, name='archive_attachment'),
    path('msg/<list_name>/<id>/download/', views.message_download, name='archive_message_download'),
    path('search/', views.CustomSearchView.as_view(), name='archive_search'),
    # reports    ----------------
    path('reports/subscribers/', views.ReportsSubscribersView.as_view(), name='reports_subscribers'),
    path('reports/messages/', views.ReportsMessagesView.as_view(), name='reports_messages'),
    # test pages ----------------
]

backend/mlarchive/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from django.views.decorators.gzip import gzip_page

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

admin.autodiscover()

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='archive',permanent=True)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='archive/login.html'), name='login'),
    path('arch/', include('mlarchive.archive.urls')),
    path('api/', include('mlarchive.archive.api_urls')),
    path('admin/', admin.site.urls),
    path('docs/', include('mlarchive.archive.docs_urls')),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('sitemap\.xml', cache_page(86400)(gzip_page(sitemap)), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend/mlarchive/archive/models.py
from email.utils import parseaddr
from email import policy as email_policy
import datetime
import email
import logging
import os
import re
import subprocess

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.http import urlencode
from django.template.loader import render_to_string

from mlarchive.archive.generator import Generator
from mlarchive.archive.thread import parse_message_ids
from mlarchive.utils.encoding import is_attachment, custom_policy


TXT2HTML = ['/usr/bin/mhonarc', '-single']
ATTACHMENT_PATTERN = r'<p><strong>Attachment:((?:.|\n)*?)</p>'
REFERENCE_RE = re.compile(r'<(.*?)>')

logger = logging.getLogger(__name__)


# --------------------------------------------------
# Helper Functions
# --------------------------------------------------


def get_in_reply_to_message(in_reply_to_value, email_list):
    '''Returns the in_reply_to message, if it exists'''
    msgids = parse_message_ids(in_reply_to_value)
    if not msgids:
        return None
    return get_message_prefer_list(msgids[0], email_list)


def get_message_from_binary_file(f, policy):
    '''Wrapper function for email.message_from_binary_file. Returns EmailMessage
    unless header parsing fails, else Message
    '''
    msg = email.message_from_binary_file(f, policy=policy)
    try:
        _ = list(msg.items())
        return msg
    except:
        f.seek(0)
        return email.message_from_binary_file(f, policy=email_policy.compat32)


def get_message_prefer_list(msgid, email_list):
    '''Returns Message (or None) prefers proivded list'''
    try:
        return Message.objects.get(msgid=msgid, email_list=email_list)
    except Message.DoesNotExist:
        return Message.objects.filter(msgid=msgid).first()


def is_ascii(text):
    try:
        text.decode('ascii')
    except UnicodeDecodeError:
        return False
    return True


def is_small_year(email_list, year):
    count = Message.objects.filter(email_list=email_list, date__year=year).count()
    return count < settings.STATIC_INDEX_YEAR_MINIMUM


# --------------------------------------------------
# Models
# --------------------------------------------------


class Thread(models.Model):
    date = models.DateTimeField(db_index=True)     # date of first message
    email_list = models.ForeignKey('EmailList', db_index=True, on_delete=models.CASCADE, null=True)
    # first message in thread, by date
    first = models.ForeignKey('Message', on_delete=models.SET_NULL, related_name='thread_key', blank=True, null=True)

    def __str__(self):
        return str(self.id)

    def get_snippet(self):
        """Returns all messages of the thread as an HTML snippet"""
        context = {'messages': self.message_set.all()}
        return render_to_string('archive/thread_snippet.html', context)

    def set_first(self, message=None):
        """Sets the first message of the thread.  Call when adding or removing
        messages
        """
        if not message:
            message = self.message_set.all().order_by('date').first()
        self.first = message
        self.date = message.date
        self.save()

    def get_next(self):
        """Returns next thread in the list"""
        return Thread.objects.filter(email_list=self.email_list, date__gt=self.date).order_by('date').first()

    def get_previous(self):
        """Returns previous thread in the list"""
        return Thread.objects.filter(email_list=self.email_list, date__lt=self.date).order_by('-date').first()


class EmailList(models.Model):
    active = models.BooleanField(default=True, db_index=True)
    alias = models.CharField(max_length=65, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=255, blank=True)
    members = models.ManyToManyField(User, blank=True)
    members_digest = models.CharField(max_length=32, blank=True)
    name = models.CharField(max_length=65, db_index=True, unique=True)
    private = models.BooleanField(default=False, db_index=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_attachments_dir(listname):
        return os.path.join(settings.ARCHIVE_DIR, listname, '_attachments')

    @property
    def attachments_dir(self):
        return self.get_attachments_dir(self.name)

    @staticmethod
    def get_failed_dir(listname):
        return os.path.join(settings.ARCHIVE_DIR, listname, '_failed')

    @property
    def failed_dir(self):
        return self.get_failed_dir(self.name)

    @staticmethod
    def get_removed_dir(listname):
        return os.path.join(settings.ARCHIVE_DIR, listname, '_removed')

    @property
    def removed_dir(self):
        return self.get_removed_dir(self.name)


class Message(models.Model):
    base_subject = models.CharField(max_length=512, blank=True, db_index=True)
    cc = models.TextField(blank=True, default='')
    date = models.DateTimeField(db_index=True)
    email_list = models.ForeignKey(EmailList, db_index=True, on_delete=models.PROTECT)
    frm = models.CharField(max_length=255, blank=True, db_index=True)
    from_line = models.CharField(max_length=255, blank=True)
    hashcode = models.CharField(max_length=28, db_index=True)
    in_reply_to = models.ForeignKey('self', null=True, related_name='replies', on_delete=models.SET_NULL)
    in_reply_to_value = models.TextField(blank=True, default='')
    # mapping to MHonArc message number
    legacy_number = models.IntegerField(blank=True, null=True, db_index=True)
    msgid = models.CharField(max_length=998, db_index=True) # See RFC 2822
    references = models.TextField(blank=True, default='')
    spam_score = models.IntegerField(default=0)             # > 0 = spam
    subject = models.CharField(max_length=512, blank=True)
    thread = models.ForeignKey(Thread, on_delete=models.PROTECT)
    thread_depth = models.IntegerField(default=0)
    thread_order = models.IntegerField(default=0)
    to = models.TextField(blank=True, default='')
    updated = models.DateTimeField(auto_now=True, db_index=True)
    # date_index_page = models.CharField(max_length=64, default='')
    # thread_index_page = models.CharField(max_length=64, default='')

    class Meta:
        indexes = [models.Index(fields=['email_list', 'date'])]

    def __str__(self):
        return self.msgid

    def as_html(self):
        """Returns the message formated as HTML.  Uses MHonarc standalone
        Not used as of v1.00
        """
        with open(self.get_file_path()) as f:
            mhout = subprocess.check_output(TXT2HTML, stdin=f)

        # extract body
        within = False
        body = []
        for line in mhout.splitlines():
            if line == '<!--X-Body-of-Message-End-->':
                within = False
            if within:
                body.append(line)
            if line == '<!--X-Body-of-Message-->':
                within = True

        str = '\n'.join(body)

        # strip attachment links
        body = re.sub(ATTACHMENT_PATTERN, '', str)

        return body

    @property
    def frm_email(self):
        """This property is the email portion of the "From" header all lowercase
        (the realname is stripped).
        """
        return parseaddr(self.frm)[1].lower()

    @property
    def frm_name(self):
        """This property is the realname portion of the "From" header if it exists.
        Otherwise returns the local-part of the email address
        """
        realname, email = parseaddr(self.frm)
        if realname:
            return realname
        else:
            return email.split('@')[0]

    @property
    def url(self):
        '''Map for index.result.url'''
        return self.get_absolute_url()

    @property
    def django_id(self):
        '''Map for index.result.django_id'''
        return str(self.id)

    @property
    def pymsg(self):
        '''A lazy attribute for the Python message object, email.EmailMessage.
        Use this for direct access to message for headers, body etc.
        '''
        if hasattr(self, '_pymsg'):
            return self._pymsg
        else:
            try:
                with open(self.get_file_path(), 'rb') as f:
                    self._pymsg = get_message_from_binary_file(f, policy=custom_policy)
                    self._pymsg_error = ''
            except IOError:
                logger.error('Error reading message file: %s' % self.get_file_path())
                self._pymsg = None
                self._pymsg_error = 'Error reading message file'
            return self._pymsg
    
    @property
    def pymsg_error(self):
        '''Any errors trying to get Python message, self.pymsg'''
        if not hasattr(self, '_pymsg_error'):
            _ = self.pymsg
        return self._pymsg_error
    
    def get_absolute_url(self):
        # strip padding, "=", to shorten URL
        return reverse('archive_detail', kwargs={
            'list_name': self.email_list.name,
            'id': self.hashcode.rstrip('=')})

    def get_absolute_url_with_host(self):
        # strip padding, "=", to shorten URL
        return settings.ARCHIVE_HOST_URL + reverse('archive_detail', kwargs={
            'list_name': self.email_list.name,
            'id': self.hashcode.rstrip('=')})

    def get_admin_url(self):
        return reverse('archive_admin') + '?' + urlencode(dict(msgid=self.msgid))

    def get_attachment_path(self):
        path = self.email_list.attachments_dir
        if not os.path.exists(path):
            os.makedirs(path)
            os.chmod(path, 0o2777)
        return path

    def get_body(self):
        """Returns the contents of the message body, text only for use in indexing.
        ie. HTML is stripped.  This is called from the index template.
        """
        gen = Generator(self)
        return gen.as_text()

    def get_body_html(self, request=None):

backend/mlarchive/templates/archive/admin.html
{% extends "base.html" %}
{% load static django_bootstrap5 widget_tweaks %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" type="text/css">
{% endblock %}

{% block title %}Mail Archive - Admin{% endblock %}

{% block header %}{{ block.super }} - Admin{% endblock %}

{% block content %}

<div class="container-fluid admin-page">
    <div class="admin-top mt-4">
        <div id="admin-view-pane" class="d-none"></div>
        <div id="admin_search_form">
            <form id="id_admin_form" name="admin-search-form" action="." method="get">
                <div class="row mb-3">
                    <div class="col-md-4 offset-md-2">
                        {% render_field form.subject class="form-control" placeholder="Subject" %}
                    </div>
                    <div class="col-md-4">
                        {% render_field form.msgid class="form-control" placeholder="Message-Id" %}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-2 offset-md-2">
                        {% render_field form.frm class="form-control" placeholder="From" %}
                    </div>
                    <div class="col-md-2">
                        {% render_field form.spam_score class="form-control" placeholder="Spam Score" %}
                    </div>
                    <div class="col-md-4">
                        {% render_field form.email_list class="form-control" placeholder="Email List Name (one or more separated by spaces)" %}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4 offset-md-2">
                        <div class="row">
                            <div class="col">
                              {% render_field form.start_date class="form-control" placeholder="Start Date" %}
                            </div>
                            <div class="col">
                                {% render_field form.end_date class="form-control" placeholder="End Date" %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <button class="btn btn-secondary" type="submit">Search</button>
                    </div>
                    <div class="col-md-3 form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="exclude-checkbox" name="exclude_whitelisted_senders" value="exclude_whitelisted_senders">
                        <label class="form-check-label" for="exclude-checkbox">Exclude Whitelisted Senders</label>
                    </div>
                </div>
            </form>
        </div> <!-- admin_search_form -->
    </div> <!-- admin-top -->

    <div id="result-list" class="section" tabindex="-1">
        <h3>Results{% if results %} ({{ results|length }}){% endif %}</h3>
        <form id="id_admin_action" name="admin-action-form" action="." method="post">{% csrf_token %}

        <div class="row mb-3">
            <div class="col-md-1 offset-md-1 form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="selectall" name="selectall" value="selectall">
                <label class="form-check-label" for="selectall">Select All</label>
            </div>
            <div class="col-md-4 d-flex">
                <label class="visually-hidden" for="action-select">Action</label>
                {{ action_form.action.errors }}
                <select id="action-select" name="action" class="form-control" placeholder="Select action">
                    <option value="" selected="selected" disabled>Select Action</option>
                    <option value="remove_selected">Remove selected messages</option>
                    <option value="not_spam">Mark selected not spam</option>
                </select>
                <input type="hidden" class="select-across" value="0" name="select_across" />
                <button type="submit" class="btn btn-secondary" title="Run the selected action" name="index" value="0">Go</button>
            </div>
            <div class="col-md-4">
                <div class="d-flex">
                    <div class="btn-group me-2" role="group" aria-label="spam buttons">
                        <button id="spam-toggle" type="button" class="btn btn-primary" data-bs-toggle="button" aria-pressed="false" autocomplete="off">Spam Mode</button>
                        <button id="spam-process" type="button" class="btn btn-primary disabled" data-bs-toggle="button" aria-pressed="false" autocomplete="off">Process Spam</button>
                    </div>
                    <div class="spinner d-none">
                        <i class="fa fa-sync-alt fa-spin fa-2x"></i>
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-check form-check-inline d-none">
                    <label class="form-check-label" for="move-subject">Move identical subject</label>
                    <input class="form-check-input" type="checkbox" id="move-subject" value="" checked>
                </div>
            </div>
        </div> <!-- row -->

        <div class="spam-top d-none">
          <div class="alert alert-warning" role="alert">Use left and right arrow keys to sort messages.  Right = spam, Left = not spam.  Use Process Spam button to remove spam and mark clean messages.</div>
          <ul class="nav nav-tabs nav-justified">
            <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#clean-pane">Clean - 0</a></li>
            <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#search-pane">Search - {{ results|length }}</a></li>
            <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#spam-pane">Spam - 0</a></li>
          </ul>
        </div>

        <div class="tab-content" tabindex="0">
            <div id="clean-pane" class="tab-pane">
                {% include "includes/admin_results.html" %}
            </div>
            <div id="search-pane" class="tab-pane active">
                {% with admin_results=results %}
                    {% include "includes/admin_results.html" %}
                {% endwith %}
            </div>
            <div id="spam-pane" class="tab-pane">
                {% include "includes/admin_results.html" %}
            </div>
        </div> <!-- tab-content -->
        
        </form>
</div> <!-- result-list -->
</div> <!-- admin-page -->
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}

{% block modal %}
<div id="spam-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          <h4 class="modal-title">Spam</h4>
        </div>
        <div class="modal-body">
          <p>Move all messages with the same subject to spam?</p>
        </div>
        <div class="modal-footer">
          <button id="yes-move" type="button" class="btn btn-secondary">Yes</button>
          <button id="no-move" type="button" class="btn btn-secondary">No</button>
        </div>
    </div>

  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'mlarchive/js/admin.js' %}"></script>
{% endblock %}

backend/mlarchive/templates/archive/ajax_msg.html
<div id="msg-body">
    <h2>{{ msg.subject }}</h2>
    <pre class="">{{ msg.body }}</pre>
</div>
<div id="msg-link"><a class="msg-link" href="http://{{ request.META.HTTP_HOST }}{% url "archive_detail" list_name=msg.email_list.name id=msg.hashcode %}">http://{{ request.META.HTTP_HOST }}{% url "archive_detail" list_name=msg.email_list.name id=msg.hashcode %}</a></div>

backend/mlarchive/templates/archive/api_reference.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.14.0/swagger-ui.css" >
{% endblock %}

{% block title %}API Reference{% endblock %}

{% block content %}
<div id="swagger-ui"></div>
{% endblock %}

{% block footer %}{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.14.0/swagger-ui-bundle.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.14.0/swagger-ui-standalone-preset.js"> </script>
<script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "https://raw.githubusercontent.com/ietf-tools/mailarch/main/api.yml",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
      });
      // End Swagger UI call region

      window.ui = ui;
    };
</script>
{% endblock %}

backend/mlarchive/templates/archive/export.html
{% extends "base.html" %}
{% load static %}

{% block title %}Archive - Export{% endblock %}

{% block content %}

<div id="export-page" class="container-fluid">
  <h3>Archive Export</h3>
  <hr>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4"><strong>Export Type:</strong> {{ type|upper }}</div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4"><strong>Number of messages:</strong> {{ count }}</div>
    </div>
    {% if type != "url" %}
    <div class="row">
      <div class="col-md-4 col-md-offset-4"><strong>Estimated Size:</strong> {{ estimated_size }}k</div>
    </div>
    {% endif %}
  </div>

  <form action="" method="post">{% csrf_token %}
    <ul class="export-buttons">
      <li><button class="btn btn-secondary" onclick="history.go(-1);return false">Back</button></li>
      <li><button class="btn btn-secondary" type="submit">Continue</button></li>
    </ul>
  </form>

</div>

{% endblock %}

backend/mlarchive/templates/archive/load.html
{% extends "base.html" %}

{% block extrahead %}
{% endblock %} 

{% block title %}Mail Archive{% endblock %}

{% block content %}

<ul>
  {% for member in members %}
    <li>{{ member }}</li>
  {% endfor %}
</ul>


{% endblock %}

backend/mlarchive/templates/archive/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Mail Archive{% endblock %}

{% block content %}

<div class="corral">
  <div class="login-container">
    <form action="." method="post">{% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <div class="d-grid">
          <button id="login-button" type="submit" value="Login" class="btn btn-primary">Log In</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
  </div>  <!-- login-container -->
</div> <!-- .corral -->

{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
    $('#id_username').focus();
});
</script>
{% endblock %}

backend/mlarchive/templates/archive/message_html.html
<iframe>{{ payload|safe }}</iframe>

backend/mlarchive/templates/archive/message_plain.html
<pre class="wordwrap">{{ payload }}</pre>

backend/mlarchive/templates/archive/removed.html
{% extends "base.html" %}

{% block extrahead %}
{% endblock %} 

{% block title %}Mail Archive{% endblock %}

{% block content %}

<h3>This message has been removed from the archive.</h3>

{% endblock %}

backend/mlarchive/templates/archive/reports_subscribers.html
{% extends "base.html" %}
{% load static %}

{% block title %}Mail Archive - Subscribers{% endblock %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/jquery.dataTables.min.css' %}">
{% endblock %}

{% block content %}

<h3 class="text-center mt-4">List Subscribers</h3>
<h6 class="text-center text-muted mb-4">Date: {{ date|date:"Y-m-d" }}</h6>
<div class="row results mt-2">
  <div class="col-md-6 offset-md-3">
    <table class="smart-table compact stripe">
      <thead>
        <tr>
          <th>List Name</th>
          <th>Subscribers</th>
        </tr>
      </thead>
      <tbody>
      {% for subscriber in object_list %}
        <tr>
          <td>{{ subscriber.email_list.name }}</td>
          <td>{{ subscriber.count }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div> <!-- col -->

  <div class="col-md-3">
    <form action="." method="get">
      <div class="row mb-3 mt-2">
        <div class="col-md-10 offset-md-1">
          <label for="id_date">Date</label>
          <input type="text" name="date" placeholder="YYYY-MM-DD" class="form-control" id="id_date">
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-10 offset-md-1">
          <input class="btn btn-primary w-100" type="submit" value="Submit">
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-10 offset-md-1">
          <p class="text-muted">Historic data, before Jan 2023, is only available monthly,
            so use the first day of the month. e.g. 2021-04-01
          </p>
        </div>
      </div>
    </form>
    <div class="row mt-5">
        <div class="col-md-10 offset-md-1">
          <a class="btn btn-primary w-100" href="?{{ export_query_string }}">Export</a>
          <p class="text-muted mt-3">Export data as csv file</p>
        </div>
    </div>
  </div> <!-- col -->

</div> <!-- row -->

{% endblock %}

{% block footer %}
  {% with extra_class="scrolling" %}
    {% include "includes/footer.html" %}
  {% endwith %}
{% endblock %}

{% block js %}
  <script src="{% static 'datatables/js/jquery.dataTables.min.js' %}" crossorigin="anonymous"></script>
  <script>
    $('.smart-table').DataTable({
      paging: false,
      searching: false,
      info: false
  });
  </script>
{% endblock %}

backend/mlarchive/templates/archive/static_index.html
{% extends "base.html" %}
{% load static archive_extras %}

{% block title %}{{ email_list.name }} Discussion Archive - {% if group_by_thread %}Thread{% else %}Date{% endif %} Index - {{ date_string }}{% endblock %}

{% block content %}

    <div class="static-page container-fluid">
        <h3 class="mt-4">{{ email_list.name }} Discussion Archive - {% if group_by_thread %}Thread{% else %}Date{% endif %} Index - {{ date_string }}</h3>

        {% include "includes/static_index_nav.html" %}

        <ul class="static-index" data-static-off-url="{{ static_off_url }}">
        {% for message in queryset %}
            {% if group_by_thread %}
                <li class="depth-{{ message.thread_depth|max_depth }}">
                    <a id="{{ message.hashcode|slice:':-1' }}" href="{{ message.get_absolute_url }}">{{ message.subject }}</a>, <em>{{ message.frm_name }}</em>
                </li>
            {% else %}
                {% with date=message.date|date:"M d Y" %}
                    {% ifchanged %}<strong>{{ date }}</strong>{% endifchanged %}
                    <li>
                        <a id="{{ message.hashcode|slice:':-1' }}" href="{{ message.get_absolute_url }}">{{ message.subject }}</a>, <em>{{ message.frm_name }}</em>
                    </li>
                {% endwith %}
            {% endif %}        
        {% empty %}
            <li>No messages</li>
        {% endfor %}
        </ul>
        <hr>

        {% include "includes/static_index_nav.html" %}

    </div> <!-- static-page -->

{% endblock %}

{% block footer %}{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'mlarchive/js/static_index.js' %}"></script>
{% endblock %}